Warning time
egedebruin/Trackscape pull request #77
Opened 2018-06-19 10:37 UTC by egedebruin

Shows a warning to the game host according to a given warning time in the configuration file

2018-06-19 19:21 UTC, lisv reviewed
The code looks good! I will test it with the configuration file of the stream tomorrow.

2018-06-20 11:57 UTC, Jasperkroes requested changes
als de warning pane wordt gesnoozed nadat de warningtime is geweest, dan kan het zijn dat er geen warning te zien is direct nadat de targettime overschreden word. Misschien moet de snoozetimer gerestet worden op het moment dat de tijd rood wordt.

2018-06-20 13:07 UTC, egedebruin commented
@Jasperkroes  fixed

2018-06-20 14:47 UTC, Jasperkroes submitted a review, later dismissed
lekker bezig hoor, dr is alleen wel 1 ding dat fout kan gaan, maar dat is niet zo erg anders wordt ie misschine niet gemerged

2018-06-21 08:42 UTC, Jasperkroes commented
Ik denk dat het het best is als we eerst #70 mergen en daarna pas deze branch. Aangezien #70 belangrijker is en we niet heel veel tijd meer hebben.

2018-06-22 07:39 UTC, lisv commented
Als de warning verschijnt voor een kist maar het team opent deze kist en gaat door naar de volgende (die weer met groene tekst en timer 0:00) begint, dan verdwijnt de warning niet

2018-06-22 08:39 UTC, egedebruin commented
NU IS T GEFIXT GOGO EGEL

2018-06-22 08:39 UTC, lisv approved these changes
Seems to work fine.

2018-06-22 09:12 UTC, lisv commented
Ik krijg geen warning meer als target time wordt overschreden

2018-06-22 09:15 UTC, robinjo78 commented on src/main/java/gui/panes/ManualConfigPane.java
> +            if (!(checkNegativeNumbers(sectionInt, error) | checkNegativeNumbers(durationInt, error)
Goeie oplossing!

2018-06-22 09:18 UTC, robinjo78 commented on src/test/java/room/RoomTest.java
>      void setNextChestOpened() {
Moet er geen test in de naam?

2018-06-22 09:18 UTC, robinjo78 commented on src/test/java/room/RoomTest.java
>      void setNextSectionOpened() {
Same

2018-06-22 09:38 UTC, robinjo78 approved these changes
Werkt goed!

2018-06-22 10:32 UTC, Jasperkroes requested changes
er wordt nu alleen een warning getoond als de warning time wordt overschreden

2018-06-22 10:41 UTC, egedebruin commented
gefixt @Jasperkroes

2018-06-22 10:53 UTC, lisv approved these changes

2018-06-22 10:59 UTC, Jasperkroes commented
kunnen we de tekst oranje maken als de warning time is overschreden?

2018-06-22 10:59 UTC, egedebruin commented
ja

2018-06-22 11:00 UTC, Jasperkroes commented
oke laat maar zien

2018-06-22 11:00 UTC, egedebruin commented
ik heb niks te bewijzen

2018-06-22 11:25 UTC, Jasperkroes approved these changes
oke geen oranje tekst dus

2018-06-22 11:25 UTC, merged